server:
  port: 8081
  servlet:
    context-path: /multiple-datasource-connection
spring:
  user:
    datasource:
      jdbc-url: jdbc:mysql://localhost:3306/user
      username: root
      password: root

  booking:
    datasource:
      jdbc-url: jdbc:mysql://localhost:3306/booking
      username: root
      password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect